spring:
  application:
     name: njaucommunity
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///njaucommunity?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

mybatis:
  config-location: classpath:/mybatis-config.xml
#mybatis:
#  mapper-locations: classpath:*/mapper/*.xml

server:
  port: 8088